//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STW.UNSK.Personal.Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string Surname { get; set; }
        public int Post_Id { get; set; }
        public int Num { get; set; }
        public bool Hidden { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
